### ISSUE TITLE
Slider seems not working.

### ISSUE THREAD

**Issue by shidhincr** [addyosmani/smaller-pictures-app#17]
The slider seems not working. Please check the the below GIF

![](http://g.recordit.co/CnVPTVwIUw.gif)

Browser:
Chrome ( Version 56.0.2924.87 (64-bit) ) on OSX 10.12.3

**Comment by Semigradsky** [comment]
It's just not implemented

**Comment by addyosmani** [comment]
The slider was implemented when I deployed the app last. Confirmed latest isn't working. I'm going to investigate whether this is fixed in later versions of MDL.

**Comment by cheralathann** [comment]
Hi @addyosmani, I am interested to fix this issue.

**Comment by addyosmani** [comment]
Thanks, @shidhincr. Closed by your PR!

**Comment by shidhincr** [comment]
@addyosmani Thanks goes to @cheralathann 👍
